import { Word, ExamQuestion, LibraryCategory } from '../types';

// --- Vocabulary Data (Welcome Unit - Unit 5) ---
export const VOCABULARY_DATA: Word[] = [
  // --- Welcome Unit ---
  { id: 'wu-1', unit: 'Welcome Unit', english: 'exchange', phonetic: '/ɪksˈtʃeɪndʒ/', partOfSpeech: 'n. & vt.', chinese: '交换；交流', example: 'We exchange gifts during the holidays.' },
  { id: 'wu-2', unit: 'Welcome Unit', english: 'lecture', phonetic: '/ˈlektʃə(r)/', partOfSpeech: 'n. & vi.', chinese: '讲座；讲课', example: 'The professor gave a lecture on physics.' },
  { id: 'wu-3', unit: 'Welcome Unit', english: 'registration', phonetic: '/ˌredʒɪˈstreɪʃn/', partOfSpeech: 'n.', chinese: '登记；注册', example: 'Registration starts at 8 a.m.' },
  { id: 'wu-4', unit: 'Welcome Unit', english: 'register', phonetic: '/ˈredʒɪstə(r)/', partOfSpeech: 'vt. & vi.', chinese: '登记；注册', example: 'You need to register for the course.' },
  { id: 'wu-5', unit: 'Welcome Unit', english: 'sex', phonetic: '/seks/', partOfSpeech: 'n.', chinese: '性别', example: 'Please state your sex on the form.' },
  { id: 'wu-6', unit: 'Welcome Unit', english: 'female', phonetic: '/ˈfiːmeɪl/', partOfSpeech: 'adj. & n.', chinese: '女性(的)；雌性(的)', example: 'The female lion hunts.' },
  { id: 'wu-7', unit: 'Welcome Unit', english: 'male', phonetic: '/meɪl/', partOfSpeech: 'adj. & n.', chinese: '男性(的)；雄性(的)', example: 'A male voice answered.' },
  { id: 'wu-8', unit: 'Welcome Unit', english: 'nationality', phonetic: '/ˌnæʃəˈnæləti/', partOfSpeech: 'n.', chinese: '国籍；民族', example: 'What is your nationality?' },
  { id: 'wu-9', unit: 'Welcome Unit', english: 'nation', phonetic: '/ˈneɪʃn/', partOfSpeech: 'n.', chinese: '国家；民族', example: 'The whole nation celebrated.' },
  { id: 'wu-10', unit: 'Welcome Unit', english: 'designer', phonetic: '/dɪˈzaɪnə(r)/', partOfSpeech: 'n.', chinese: '设计者', example: 'A fashion designer.' },
  { id: 'wu-11', unit: 'Welcome Unit', english: 'design', phonetic: '/dɪˈzaɪn/', partOfSpeech: 'n. & vt.', chinese: '设计', example: 'They designed a new bridge.' },
  { id: 'wu-12', unit: 'Welcome Unit', english: 'campus', phonetic: '/ˈkæmpəs/', partOfSpeech: 'n.', chinese: '校园；校区', example: 'The campus is beautiful in spring.' },
  { id: 'wu-13', unit: 'Welcome Unit', english: 'formal', phonetic: '/ˈfɔːml/', partOfSpeech: 'adj.', chinese: '正式的；正规的', example: 'Wear formal clothes.' },
  { id: 'wu-14', unit: 'Welcome Unit', english: 'anxious', phonetic: '/ˈæŋkʃəs/', partOfSpeech: 'adj.', chinese: '焦虑的；不安的', example: 'I felt anxious before the test.' },
  { id: 'wu-15', unit: 'Welcome Unit', english: 'annoyed', phonetic: '/əˈnɔɪd/', partOfSpeech: 'adj.', chinese: '恼怒的；生气的', example: 'He was annoyed by the noise.' },
  { id: 'wu-16', unit: 'Welcome Unit', english: 'annoy', phonetic: '/əˈnɔɪ/', partOfSpeech: 'vt.', chinese: '使恼怒；打扰', example: 'Don\'t annoy the dog.' },
  { id: 'wu-17', unit: 'Welcome Unit', english: 'frightened', phonetic: '/ˈfraɪtnd/', partOfSpeech: 'adj.', chinese: '惊吓的；害怕的', example: 'She was frightened of the dark.' },
  { id: 'wu-18', unit: 'Welcome Unit', english: 'p.m.', phonetic: '/ˌpiː ˈem/', partOfSpeech: 'abbr.', chinese: '下午', example: 'Let\'s meet at 3 p.m.' },
  { id: 'wu-19', unit: 'Welcome Unit', english: 'a.m.', phonetic: '/ˌeɪ ˈem/', partOfSpeech: 'abbr.', chinese: '上午', example: 'The class starts at 9 a.m.' },
  { id: 'wu-20', unit: 'Welcome Unit', english: 'senior', phonetic: '/ˈsiːniə(r)/', partOfSpeech: 'adj. & n.', chinese: '级别高的；较年长的人', example: 'He is a senior manager.' },
  { id: 'wu-21', unit: 'Welcome Unit', english: 'senior high school', phonetic: '', partOfSpeech: 'n.', chinese: '(美国)高中', example: 'I am a student at senior high school.' },
  { id: 'wu-22', unit: 'Welcome Unit', english: 'at last', phonetic: '', partOfSpeech: '', chinese: '终于；最终', example: 'At last, we arrived.' },
  { id: 'wu-23', unit: 'Welcome Unit', english: 'outgoing', phonetic: '/ˈaʊtɡəʊɪŋ/', partOfSpeech: 'adj.', chinese: '爱交际的；外向的', example: 'She has an outgoing personality.' },
  { id: 'wu-24', unit: 'Welcome Unit', english: 'impression', phonetic: '/ɪmˈpreʃn/', partOfSpeech: 'n.', chinese: '印象；感想', example: 'First impressions are important.' },
  { id: 'wu-25', unit: 'Welcome Unit', english: 'impress', phonetic: '/ɪmˈpres/', partOfSpeech: 'vt.', chinese: '使钦佩；留下深刻印象', example: 'He tried to impress the teacher.' },
  { id: 'wu-26', unit: 'Welcome Unit', english: 'make an impression', phonetic: '', partOfSpeech: '', chinese: '留下好印象', example: 'I want to make a good impression.' },
  { id: 'wu-27', unit: 'Welcome Unit', english: 'what if', phonetic: '', partOfSpeech: '', chinese: '要是...会怎么样呢？', example: 'What if it rains?' },
  { id: 'wu-28', unit: 'Welcome Unit', english: 'guy', phonetic: '/ɡaɪ/', partOfSpeech: 'n.', chinese: '小伙子；男人；家伙', example: 'He\'s a nice guy.' },
  { id: 'wu-29', unit: 'Welcome Unit', english: 'concentrate', phonetic: '/ˈkɒnsntreɪt/', partOfSpeech: 'vi. & vt.', chinese: '集中(注意力)', example: 'Concentrate on your work.' },
  { id: 'wu-30', unit: 'Welcome Unit', english: 'concentrate on', phonetic: '', partOfSpeech: '', chinese: '集中精力于', example: 'Concentrate on the road.' },
  { id: 'wu-31', unit: 'Welcome Unit', english: 'experiment', phonetic: '/ɪkˈsperɪmənt/', partOfSpeech: 'n. & vi.', chinese: '实验；试验', example: 'Conduct an experiment.' },
  { id: 'wu-32', unit: 'Welcome Unit', english: 'leave... alone', phonetic: '', partOfSpeech: '', chinese: '不打扰；不惊动', example: 'Leave the cat alone.' },
  { id: 'wu-33', unit: 'Welcome Unit', english: 'awkward', phonetic: '/ˈɔːkwəd/', partOfSpeech: 'adj.', chinese: '令人尴尬的；难对付的', example: 'An awkward silence.' },
  { id: 'wu-34', unit: 'Welcome Unit', english: 'junior', phonetic: '/ˈdʒuːniə(r)/', partOfSpeech: 'adj. & n.', chinese: '地位低下的；初级', example: 'Junior staff.' },
  { id: 'wu-35', unit: 'Welcome Unit', english: 'junior high school', phonetic: '', partOfSpeech: 'n.', chinese: '(美国)初级中学', example: 'She is in junior high school.' },
  { id: 'wu-36', unit: 'Welcome Unit', english: 'explore', phonetic: '/ɪkˈsplɔː(r)/', partOfSpeech: 'vt. & vi.', chinese: '探索；勘探', example: 'Explore the city.' },
  { id: 'wu-37', unit: 'Welcome Unit', english: 'confident', phonetic: '/ˈkɒnfɪdənt/', partOfSpeech: 'adj.', chinese: '自信的；有把握的', example: 'Be confident in yourself.' },
  { id: 'wu-38', unit: 'Welcome Unit', english: 'confidence', phonetic: '/ˈkɒnfɪdəns/', partOfSpeech: 'n.', chinese: '信心；信任', example: 'I have confidence in you.' },
  { id: 'wu-39', unit: 'Welcome Unit', english: 'forward', phonetic: '/ˈfɔːwəd/', partOfSpeech: 'adv. & adj.', chinese: '向前；前进', example: 'Look forward.' },
  { id: 'wu-40', unit: 'Welcome Unit', english: 'look forward to', phonetic: '', partOfSpeech: '', chinese: '盼望；期待', example: 'I look forward to meeting you.' },
  { id: 'wu-41', unit: 'Welcome Unit', english: 'take notes', phonetic: '', partOfSpeech: '', chinese: '记笔记', example: 'Take notes during the lecture.' },
  { id: 'wu-42', unit: 'Welcome Unit', english: 'flash', phonetic: '/flæʃ/', partOfSpeech: 'n. & vi.', chinese: '光；信号；闪耀', example: 'A flash of light.' },
  { id: 'wu-43', unit: 'Welcome Unit', english: 'flash card', phonetic: '', partOfSpeech: '', chinese: '教学卡片；识字卡', example: 'Use flash cards to study.' },
  { id: 'wu-44', unit: 'Welcome Unit', english: 'organise', phonetic: '/ˈɔːɡənaɪz/', partOfSpeech: 'vt.', chinese: '组织；筹备', example: 'Organise a meeting.' },
  { id: 'wu-45', unit: 'Welcome Unit', english: 'organization', phonetic: '/ˌɔːɡənaɪˈzeɪʃn/', partOfSpeech: 'n.', chinese: '组织；团体', example: 'A large organization.' },
  { id: 'wu-46', unit: 'Welcome Unit', english: 'goal', phonetic: '/ɡəʊl/', partOfSpeech: 'n.', chinese: '目标；球门', example: 'Score a goal.' },
  { id: 'wu-47', unit: 'Welcome Unit', english: 'strategy', phonetic: '/ˈstrætədʒi/', partOfSpeech: 'n.', chinese: '策略；策划', example: 'A marketing strategy.' },
  { id: 'wu-48', unit: 'Welcome Unit', english: 'partner', phonetic: '/ˈpɑːtnə(r)/', partOfSpeech: 'n.', chinese: '同伴；配偶', example: 'Work with a partner.' },
  { id: 'wu-49', unit: 'Welcome Unit', english: 'improve', phonetic: '/ɪmˈpruːv/', partOfSpeech: 'vi. & vt.', chinese: '改善；改进', example: 'Improve your English.' },

  // --- Unit 1: Teenage Life ---
  { id: 'u1-1', unit: 'Unit 1', english: 'teenage', phonetic: '/ˈtiːneɪdʒ/', partOfSpeech: 'adj.', chinese: '十几岁的；青少年的', example: 'Teenage years are formative.' },
  { id: 'u1-2', unit: 'Unit 1', english: 'teenager', phonetic: '/ˈtiːneɪdʒə(r)/', partOfSpeech: 'n.', chinese: '青少年', example: 'He is a teenager.' },
  { id: 'u1-3', unit: 'Unit 1', english: 'ballet', phonetic: '/ˈbæleɪ/', partOfSpeech: 'n.', chinese: '芭蕾舞', example: 'She practices ballet.' },
  { id: 'u1-4', unit: 'Unit 1', english: 'volunteer', phonetic: '/ˌvɒlənˈtɪə(r)/', partOfSpeech: 'n. & vi.', chinese: '志愿者', example: 'Work as a volunteer.' },
  { id: 'u1-5', unit: 'Unit 1', english: 'debate', phonetic: '/dɪˈbeɪt/', partOfSpeech: 'n. & vi.', chinese: '辩论；争论', example: 'A debate about school rules.' },
  { id: 'u1-6', unit: 'Unit 1', english: 'prefer', phonetic: '/prɪˈfɜː(r)/', partOfSpeech: 'vt.', chinese: '较喜欢', example: 'I prefer tea to coffee.' },
  { id: 'u1-7', unit: 'Unit 1', english: 'content', phonetic: '/ˈkɒntent/', partOfSpeech: 'n.', chinese: '内容；目录', example: 'Table of content.' },
  { id: 'u1-8', unit: 'Unit 1', english: 'movement', phonetic: '/ˈmuːvmənt/', partOfSpeech: 'n.', chinese: '动作；运动', example: 'The movement of the dancers.' },
  { id: 'u1-9', unit: 'Unit 1', english: 'greenhouse', phonetic: '/ˈɡriːnhaʊs/', partOfSpeech: 'n.', chinese: '温室；暖房', example: 'Plants grow in a greenhouse.' },
  { id: 'u1-10', unit: 'Unit 1', english: 'clean up', phonetic: '', partOfSpeech: '', chinese: '打扫(或清除)干净', example: 'Clean up your room.' },
  { id: 'u1-11', unit: 'Unit 1', english: 'suitable', phonetic: '/ˈsuːtəbl/', partOfSpeech: 'adj.', chinese: '合适的；适用的', example: 'Suitable for children.' },
  { id: 'u1-12', unit: 'Unit 1', english: 'actually', phonetic: '/ˈæktʃuəli/', partOfSpeech: 'adv.', chinese: '事实上；的确', example: 'Actually, I don\'t know.' },
  { id: 'u1-13', unit: 'Unit 1', english: 'challenge', phonetic: '/ˈtʃælɪndʒ/', partOfSpeech: 'n. & vt.', chinese: '挑战', example: 'Face the challenge.' },
  { id: 'u1-14', unit: 'Unit 1', english: 'title', phonetic: '/ˈtaɪtl/', partOfSpeech: 'n.', chinese: '标题；头衔', example: 'The title of the book.' },
  { id: 'u1-15', unit: 'Unit 1', english: 'topic', phonetic: '/ˈtɒpɪk/', partOfSpeech: 'n.', chinese: '话题；标题', example: 'Topic of discussion.' },
  { id: 'u1-16', unit: 'Unit 1', english: 'freshman', phonetic: '/ˈfreʃmən/', partOfSpeech: 'n.', chinese: '(大学)一年级新生', example: 'He is a college freshman.' },
  { id: 'u1-17', unit: 'Unit 1', english: 'confusing', phonetic: '/kənˈfjuːzɪŋ/', partOfSpeech: 'adj.', chinese: '难以理解的', example: 'The instructions are confusing.' },
  { id: 'u1-18', unit: 'Unit 1', english: 'confuse', phonetic: '/kənˈfjuːz/', partOfSpeech: 'vt.', chinese: '使困惑', example: 'Don\'t confuse me.' },
  { id: 'u1-19', unit: 'Unit 1', english: 'confused', phonetic: '/kənˈfjuːzd/', partOfSpeech: 'adj.', chinese: '困惑的', example: 'I am confused.' },
  { id: 'u1-20', unit: 'Unit 1', english: 'fluent', phonetic: '/ˈfluːənt/', partOfSpeech: 'adj.', chinese: '流利的', example: 'Fluent in English.' },
  { id: 'u1-21', unit: 'Unit 1', english: 'graduate', phonetic: '/ˈɡrædʒuət/', partOfSpeech: 'vi. & vt.', chinese: '毕业', example: 'Graduate from school.' },
  { id: 'u1-22', unit: 'Unit 1', english: 'recommend', phonetic: '/ˌrekəˈmend/', partOfSpeech: 'vt.', chinese: '建议；推荐', example: 'I recommend this book.' },
  { id: 'u1-23', unit: 'Unit 1', english: 'sign up', phonetic: '', partOfSpeech: '', chinese: '报名(参加课程)', example: 'Sign up for the club.' },
  { id: 'u1-24', unit: 'Unit 1', english: 'advanced', phonetic: '/ədˈvɑːnst/', partOfSpeech: 'adj.', chinese: '高级的；高等的', example: 'Advanced level.' },
  { id: 'u1-25', unit: 'Unit 1', english: 'advance', phonetic: '/ədˈvɑːns/', partOfSpeech: 'n. & vi.', chinese: '前进；发展', example: 'Technological advance.' },
  { id: 'u1-26', unit: 'Unit 1', english: 'literature', phonetic: '/ˈlɪtrətʃə(r)/', partOfSpeech: 'n.', chinese: '文学；文学作品', example: 'English literature.' },
  { id: 'u1-27', unit: 'Unit 1', english: 'extra-curricular', phonetic: '/ˌekstrəkəˈrɪkjələ/', partOfSpeech: 'adj.', chinese: '课外的', example: 'Extra-curricular activities.' },
  { id: 'u1-28', unit: 'Unit 1', english: 'extra', phonetic: '/ˈekstrə/', partOfSpeech: 'adj.', chinese: '额外的', example: 'Extra work.' },
  { id: 'u1-29', unit: 'Unit 1', english: 'obviously', phonetic: '/ˈɒbviəsli/', partOfSpeech: 'adv.', chinese: '显然；明显地', example: 'Obviously, he is wrong.' },
  { id: 'u1-30', unit: 'Unit 1', english: 'quit', phonetic: '/kwɪt/', partOfSpeech: 'vi. & vt.', chinese: '停止；戒掉；离开', example: 'Quit smoking.' },
  { id: 'u1-31', unit: 'Unit 1', english: 'responsible', phonetic: '/rɪˈspɒnsəbl/', partOfSpeech: 'adj.', chinese: '负责的', example: 'Be responsible for it.' },
  { id: 'u1-32', unit: 'Unit 1', english: 'responsibility', phonetic: '/rɪˌspɒnsəˈbɪləti/', partOfSpeech: 'n.', chinese: '责任；义务', example: 'Take responsibility.' },
  { id: 'u1-33', unit: 'Unit 1', english: 'solution', phonetic: '/səˈluːʃn/', partOfSpeech: 'n.', chinese: '解决办法', example: 'Solution to the problem.' },
  { id: 'u1-34', unit: 'Unit 1', english: 'schedule', phonetic: '/ˈʃedjuːl/', partOfSpeech: 'n.', chinese: '工作计划；日程安排', example: 'Check the schedule.' },
  { id: 'u1-35', unit: 'Unit 1', english: 'editor', phonetic: '/ˈedɪtə(r)/', partOfSpeech: 'n.', chinese: '编辑；编者', example: 'Newspaper editor.' },
  { id: 'u1-36', unit: 'Unit 1', english: 'adventure', phonetic: '/ədˈventʃə(r)/', partOfSpeech: 'n.', chinese: '冒险；奇遇', example: 'Go on an adventure.' },
  { id: 'u1-37', unit: 'Unit 1', english: 'youth', phonetic: '/juːθ/', partOfSpeech: 'n.', chinese: '青年时期', example: 'In my youth.' },
  { id: 'u1-38', unit: 'Unit 1', english: 'survival', phonetic: '/səˈvaɪvl/', partOfSpeech: 'n.', chinese: '生存；幸存', example: 'Survival skills.' },
  { id: 'u1-39', unit: 'Unit 1', english: 'expert', phonetic: '/ˈekspɜːt/', partOfSpeech: 'n.', chinese: '专家；行家', example: 'An expert in math.' },
  { id: 'u1-40', unit: 'Unit 1', english: 'behaviour', phonetic: '/bɪˈheɪvjə(r)/', partOfSpeech: 'n.', chinese: '行为；举止', example: 'Good behaviour.' },
  { id: 'u1-41', unit: 'Unit 1', english: 'generation', phonetic: '/ˌdʒenəˈreɪʃn/', partOfSpeech: 'n.', chinese: '一代(人)', example: 'The younger generation.' },
  { id: 'u1-42', unit: 'Unit 1', english: 'attract', phonetic: '/əˈtrækt/', partOfSpeech: 'vt.', chinese: '吸引', example: 'Attract attention.' },
  { id: 'u1-43', unit: 'Unit 1', english: 'focus', phonetic: '/ˈfəʊkəs/', partOfSpeech: 'vi. & vt.', chinese: '集中(精力)', example: 'Focus on the task.' },
  { id: 'u1-44', unit: 'Unit 1', english: 'addicted', phonetic: '/əˈdɪktɪd/', partOfSpeech: 'adj.', chinese: '有瘾的；上瘾的', example: 'Addicted to games.' },
  { id: 'u1-45', unit: 'Unit 1', english: 'adult', phonetic: '/ˈædʌlt/', partOfSpeech: 'n.', chinese: '成年人', example: 'Adults only.' },

  // --- Unit 2: Travelling Around ---
  { id: 'u2-1', unit: 'Unit 2', english: 'castle', phonetic: '/ˈkɑːsl/', partOfSpeech: 'n.', chinese: '城堡', example: 'Visit the castle.' },
  { id: 'u2-2', unit: 'Unit 2', english: 'apply', phonetic: '/əˈplaɪ/', partOfSpeech: 'vi. & vt.', chinese: '申请；应用', example: 'Apply for a job.' },
  { id: 'u2-3', unit: 'Unit 2', english: 'visa', phonetic: '/ˈviːzə/', partOfSpeech: 'n.', chinese: '签证', example: 'Get a visa.' },
  { id: 'u2-4', unit: 'Unit 2', english: 'rent', phonetic: '/rent/', partOfSpeech: 'vt.', chinese: '租用；出租', example: 'Rent a car.' },
  { id: 'u2-5', unit: 'Unit 2', english: 'pack', phonetic: '/pæk/', partOfSpeech: 'vi. & vt.', chinese: '收拾(行李)', example: 'Pack the luggage.' },
  { id: 'u2-6', unit: 'Unit 2', english: 'amazing', phonetic: '/əˈmeɪzɪŋ/', partOfSpeech: 'adj.', chinese: '令人惊奇的', example: 'Amazing view.' },
  { id: 'u2-7', unit: 'Unit 2', english: 'arrangement', phonetic: '/əˈreɪndʒmənt/', partOfSpeech: 'n.', chinese: '安排', example: 'Make arrangements.' },
  { id: 'u2-8', unit: 'Unit 2', english: 'extremely', phonetic: '/ɪkˈstriːmli/', partOfSpeech: 'adv.', chinese: '极其', example: 'Extremely hot.' },
  { id: 'u2-9', unit: 'Unit 2', english: 'source', phonetic: '/sɔːs/', partOfSpeech: 'n.', chinese: '来源', example: 'Source of information.' },
  { id: 'u2-10', unit: 'Unit 2', english: 'narrow', phonetic: '/ˈnærəʊ/', partOfSpeech: 'adj.', chinese: '狭窄的', example: 'A narrow street.' },
  { id: 'u2-11', unit: 'Unit 2', english: 'flat', phonetic: '/flæt/', partOfSpeech: 'adj.', chinese: '平坦的', example: 'Flat ground.' },
  { id: 'u2-12', unit: 'Unit 2', english: 'powerful', phonetic: '/ˈpaʊəfl/', partOfSpeech: 'adj.', chinese: '强有力的', example: 'A powerful engine.' },
  { id: 'u2-13', unit: 'Unit 2', english: 'empire', phonetic: '/ˈempaɪə(r)/', partOfSpeech: 'n.', chinese: '帝国', example: 'The Roman Empire.' },
  { id: 'u2-14', unit: 'Unit 2', english: 'emperor', phonetic: '/ˈempərə(r)/', partOfSpeech: 'n.', chinese: '皇帝', example: 'The emperor ruled wisely.' },
  { id: 'u2-15', unit: 'Unit 2', english: 'site', phonetic: '/saɪt/', partOfSpeech: 'n.', chinese: '地点；位置', example: 'Construction site.' },
  { id: 'u2-16', unit: 'Unit 2', english: 'official', phonetic: '/əˈfɪʃl/', partOfSpeech: 'adj.', chinese: '官方的', example: 'Official news.' },
  { id: 'u2-17', unit: 'Unit 2', english: 'recognise', phonetic: '/ˈrekəɡnaɪz/', partOfSpeech: 'vt.', chinese: '辨别出；承认', example: 'I recognise him.' },
  { id: 'u2-18', unit: 'Unit 2', english: 'type', phonetic: '/taɪp/', partOfSpeech: 'n.', chinese: '类型', example: 'Type of car.' },
  { id: 'u2-19', unit: 'Unit 2', english: 'flight', phonetic: '/flaɪt/', partOfSpeech: 'n.', chinese: '航班', example: 'Book a flight.' },
  { id: 'u2-20', unit: 'Unit 2', english: 'accommodation', phonetic: '/əˌkɒməˈdeɪʃn/', partOfSpeech: 'n.', chinese: '住处', example: 'Find accommodation.' },
  { id: 'u2-21', unit: 'Unit 2', english: 'unique', phonetic: '/juˈniːk/', partOfSpeech: 'adj.', chinese: '唯一的；独特的', example: 'A unique style.' },
  { id: 'u2-22', unit: 'Unit 2', english: 'path', phonetic: '/pɑːθ/', partOfSpeech: 'n.', chinese: '小路；路线', example: 'Follow the path.' },
  { id: 'u2-23', unit: 'Unit 2', english: 'destination', phonetic: '/ˌdestɪˈneɪʃn/', partOfSpeech: 'n.', chinese: '目的地', example: 'Final destination.' },
  { id: 'u2-24', unit: 'Unit 2', english: 'admire', phonetic: '/ədˈmaɪə(r)/', partOfSpeech: 'vt.', chinese: '钦佩；欣赏', example: 'Admire the view.' },
  { id: 'u2-25', unit: 'Unit 2', english: 'architecture', phonetic: '/ˈɑːkɪtektʃə(r)/', partOfSpeech: 'n.', chinese: '建筑设计', example: 'Modern architecture.' },
  { id: 'u2-26', unit: 'Unit 2', english: 'brochure', phonetic: '/ˈbrəʊʃə(r)/', partOfSpeech: 'n.', chinese: '资料(或广告)手册', example: 'Travel brochure.' },
  { id: 'u2-27', unit: 'Unit 2', english: 'package', phonetic: '/ˈpækɪdʒ/', partOfSpeech: 'n.', chinese: '包裹', example: 'Send a package.' },
  { id: 'u2-28', unit: 'Unit 2', english: 'contact', phonetic: '/ˈkɒntækt/', partOfSpeech: 'n. & vt.', chinese: '联系', example: 'Contact me.' },
  { id: 'u2-29', unit: 'Unit 2', english: 'civilisation', phonetic: '/ˌsɪvəlaɪˈzeɪʃn/', partOfSpeech: 'n.', chinese: '文明', example: 'Ancient civilisation.' },
  { id: 'u2-30', unit: 'Unit 2', english: 'soldier', phonetic: '/ˈsəʊldʒə(r)/', partOfSpeech: 'n.', chinese: '士兵', example: 'A brave soldier.' },
  { id: 'u2-31', unit: 'Unit 2', english: 'transport', phonetic: '/ˈtrænspɔːt/', partOfSpeech: 'n.', chinese: '交通运输', example: 'Public transport.' },
  { id: 'u2-32', unit: 'Unit 2', english: 'hike', phonetic: '/haɪk/', partOfSpeech: 'vi. & n.', chinese: '徒步旅行', example: 'Go for a hike.' },
  { id: 'u2-33', unit: 'Unit 2', english: 'economy', phonetic: '/ɪˈkɒnəmi/', partOfSpeech: 'n.', chinese: '经济', example: 'Global economy.' },
  { id: 'u2-34', unit: 'Unit 2', english: 'credit', phonetic: '/ˈkredɪt/', partOfSpeech: 'n.', chinese: '信用', example: 'Credit card.' },
  { id: 'u2-35', unit: 'Unit 2', english: 'detail', phonetic: '/ˈdiːteɪl/', partOfSpeech: 'n.', chinese: '细节', example: 'In detail.' },
  { id: 'u2-36', unit: 'Unit 2', english: 'check in', phonetic: '', partOfSpeech: '', chinese: '登记(入住)', example: 'Check in at the hotel.' },
  { id: 'u2-37', unit: 'Unit 2', english: 'request', phonetic: '/rɪˈkwest/', partOfSpeech: 'n. & vt.', chinese: '请求', example: 'Make a request.' },
  { id: 'u2-38', unit: 'Unit 2', english: 'view', phonetic: '/vjuː/', partOfSpeech: 'n.', chinese: '视野；景色', example: 'A room with a view.' },
  { id: 'u2-39', unit: 'Unit 2', english: 'sight', phonetic: '/saɪt/', partOfSpeech: 'n.', chinese: '视力；景象', example: 'Out of sight.' },
  { id: 'u2-40', unit: 'Unit 2', english: 'statue', phonetic: '/ˈstætʃuː/', partOfSpeech: 'n.', chinese: '雕像', example: 'Statue of Liberty.' },
  { id: 'u2-41', unit: 'Unit 2', english: 'tomb', phonetic: '/tuːm/', partOfSpeech: 'n.', chinese: '坟墓', example: 'Ancient tomb.' },
  { id: 'u2-42', unit: 'Unit 2', english: 'comment', phonetic: '/ˈkɒment/', partOfSpeech: 'n. & vi.', chinese: '评论', example: 'Leave a comment.' },

  // --- Unit 3: Sports and Fitness ---
  { id: 'u3-1', unit: 'Unit 3', english: 'fitness', phonetic: '/ˈfɪtnəs/', partOfSpeech: 'n.', chinese: '健康；健壮', example: 'Physical fitness.' },
  { id: 'u3-2', unit: 'Unit 3', english: 'soccer', phonetic: '/ˈsɒkə(r)/', partOfSpeech: 'n.', chinese: '足球', example: 'Play soccer.' },
  { id: 'u3-3', unit: 'Unit 3', english: 'stadium', phonetic: '/ˈsteɪdiəm/', partOfSpeech: 'n.', chinese: '体育场', example: 'Football stadium.' },
  { id: 'u3-4', unit: 'Unit 3', english: 'boxing', phonetic: '/ˈbɒksɪŋ/', partOfSpeech: 'n.', chinese: '拳击', example: 'Boxing match.' },
  { id: 'u3-5', unit: 'Unit 3', english: 'badminton', phonetic: '/ˈbædmɪntən/', partOfSpeech: 'n.', chinese: '羽毛球', example: 'Play badminton.' },
  { id: 'u3-6', unit: 'Unit 3', english: 'marathon', phonetic: '/ˈmærəθən/', partOfSpeech: 'n.', chinese: '马拉松', example: 'Run a marathon.' },
  { id: 'u3-7', unit: 'Unit 3', english: 'event', phonetic: '/ɪˈvent/', partOfSpeech: 'n.', chinese: '比赛项目；大事', example: 'Sporting event.' },
  { id: 'u3-8', unit: 'Unit 3', english: 'ski', phonetic: '/skiː/', partOfSpeech: 'adj. & vi.', chinese: '滑雪', example: 'Go skiing.' },
  { id: 'u3-9', unit: 'Unit 3', english: 'host', phonetic: '/həʊst/', partOfSpeech: 'vt. & n.', chinese: '主办；主人', example: 'Host the Olympics.' },
  { id: 'u3-10', unit: 'Unit 3', english: 'track', phonetic: '/træk/', partOfSpeech: 'n.', chinese: '跑道', example: 'Running track.' },
  { id: 'u3-11', unit: 'Unit 3', english: 'gym', phonetic: '/dʒɪm/', partOfSpeech: 'n.', chinese: '健身房', example: 'Go to the gym.' },
  { id: 'u3-12', unit: 'Unit 3', english: 'gymnastics', phonetic: '/dʒɪmˈnæstɪks/', partOfSpeech: 'n.', chinese: '体操', example: 'Do gymnastics.' },
  { id: 'u3-13', unit: 'Unit 3', english: 'sweat', phonetic: '/swet/', partOfSpeech: 'n.', chinese: '汗水', example: 'Sweat dripped down.' },
  { id: 'u3-14', unit: 'Unit 3', english: 'legend', phonetic: '/ˈledʒənd/', partOfSpeech: 'n.', chinese: '传奇', example: 'A sports legend.' },
  { id: 'u3-15', unit: 'Unit 3', english: 'athlete', phonetic: '/ˈæθliːt/', partOfSpeech: 'n.', chinese: '运动员', example: 'Professional athlete.' },
  { id: 'u3-16', unit: 'Unit 3', english: 'master', phonetic: '/ˈmɑːstə(r)/', partOfSpeech: 'n. & vt.', chinese: '大师；精通', example: 'Master a skill.' },
  { id: 'u3-17', unit: 'Unit 3', english: 'honour', phonetic: '/ˈɒnə(r)/', partOfSpeech: 'n.', chinese: '荣誉', example: 'It is an honour.' },
  { id: 'u3-18', unit: 'Unit 3', english: 'glory', phonetic: '/ˈɡlɔːri/', partOfSpeech: 'n.', chinese: '光荣', example: 'For glory.' },
  { id: 'u3-19', unit: 'Unit 3', english: 'medal', phonetic: '/ˈmedl/', partOfSpeech: 'n.', chinese: '奖牌', example: 'Gold medal.' },
  { id: 'u3-20', unit: 'Unit 3', english: 'championship', phonetic: '/ˈtʃæmpiənʃɪp/', partOfSpeech: 'n.', chinese: '锦标赛', example: 'Win the championship.' },
  { id: 'u3-21', unit: 'Unit 3', english: 'champion', phonetic: '/ˈtʃæmpiən/', partOfSpeech: 'n.', chinese: '冠军', example: 'World champion.' },
  { id: 'u3-22', unit: 'Unit 3', english: 'determination', phonetic: '/dɪˌtɜːmɪˈneɪʃn/', partOfSpeech: 'n.', chinese: '决心', example: 'With determination.' },
  { id: 'u3-23', unit: 'Unit 3', english: 'apart', phonetic: '/əˈpɑːt/', partOfSpeech: 'adv.', chinese: '分离', example: 'Fall apart.' },
  { id: 'u3-24', unit: 'Unit 3', english: 'injure', phonetic: '/ˈɪndʒə(r)/', partOfSpeech: 'vt.', chinese: '受伤', example: 'Injure his leg.' },
  { id: 'u3-25', unit: 'Unit 3', english: 'captain', phonetic: '/ˈkæptɪn/', partOfSpeech: 'n.', chinese: '队长', example: 'Team captain.' },
  { id: 'u3-26', unit: 'Unit 3', english: 'graceful', phonetic: '/ˈɡreɪsfl/', partOfSpeech: 'adj.', chinese: '优美的', example: 'Graceful dancer.' },
  { id: 'u3-27', unit: 'Unit 3', english: 'strength', phonetic: '/streŋθ/', partOfSpeech: 'n.', chinese: '力量', example: 'Physical strength.' },
  { id: 'u3-28', unit: 'Unit 3', english: 'failure', phonetic: '/ˈfeɪljə(r)/', partOfSpeech: 'n.', chinese: '失败', example: 'Fear of failure.' },
  { id: 'u3-29', unit: 'Unit 3', english: 'give up', phonetic: '', partOfSpeech: '', chinese: '放弃', example: 'Never give up.' },
  { id: 'u3-30', unit: 'Unit 3', english: 'compete', phonetic: '/kəmˈpiːt/', partOfSpeech: 'vi.', chinese: '竞争', example: 'Compete in a race.' },
  { id: 'u3-31', unit: 'Unit 3', english: 'pretend', phonetic: '/prɪˈtend/', partOfSpeech: 'vi. & vt.', chinese: '假装', example: 'Pretend to sleep.' },
  { id: 'u3-32', unit: 'Unit 3', english: 'audience', phonetic: '/ˈɔːdiəns/', partOfSpeech: 'n.', chinese: '观众', example: 'The audience clapped.' },
  { id: 'u3-33', unit: 'Unit 3', english: 'slim', phonetic: '/slɪm/', partOfSpeech: 'adj.', chinese: '苗条的', example: 'Stay slim.' },
  { id: 'u3-34', unit: 'Unit 3', english: 'diet', phonetic: '/ˈdaɪət/', partOfSpeech: 'n.', chinese: '节食；日常饮食', example: 'Go on a diet.' },
  { id: 'u3-35', unit: 'Unit 3', english: 'stress', phonetic: '/stres/', partOfSpeech: 'n.', chinese: '压力', example: 'Under stress.' },
  { id: 'u3-36', unit: 'Unit 3', english: 'error', phonetic: '/ˈerə(r)/', partOfSpeech: 'n.', chinese: '错误', example: 'Make an error.' },

  // --- Unit 4: Natural Disasters ---
  { id: 'u4-1', unit: 'Unit 4', english: 'disaster', phonetic: '/dɪˈzɑːstə(r)/', partOfSpeech: 'n.', chinese: '灾难', example: 'Natural disaster.' },
  { id: 'u4-2', unit: 'Unit 4', english: 'tornado', phonetic: '/tɔːˈneɪdəʊ/', partOfSpeech: 'n.', chinese: '龙卷风', example: 'A tornado hit.' },
  { id: 'u4-3', unit: 'Unit 4', english: 'drought', phonetic: '/draʊt/', partOfSpeech: 'n.', chinese: '旱灾', example: 'Severe drought.' },
  { id: 'u4-4', unit: 'Unit 4', english: 'flood', phonetic: '/flʌd/', partOfSpeech: 'n. & vi.', chinese: '洪水', example: 'The flood rose.' },
  { id: 'u4-5', unit: 'Unit 4', english: 'volcanic', phonetic: '/vɒlˈkænɪk/', partOfSpeech: 'adj.', chinese: '火山的', example: 'Volcanic ash.' },
  { id: 'u4-6', unit: 'Unit 4', english: 'rescue', phonetic: '/ˈreskjuː/', partOfSpeech: 'vt. & n.', chinese: '营救', example: 'Rescue team.' },
  { id: 'u4-7', unit: 'Unit 4', english: 'damage', phonetic: '/ˈdæmɪdʒ/', partOfSpeech: 'vt. & n.', chinese: '损害', example: 'Cause damage.' },
  { id: 'u4-8', unit: 'Unit 4', english: 'destroy', phonetic: '/dɪˈstrɔɪ/', partOfSpeech: 'vt.', chinese: '摧毁', example: 'Destroy the building.' },
  { id: 'u4-9', unit: 'Unit 4', english: 'evacuate', phonetic: '/ɪˈvækjueɪt/', partOfSpeech: 'vt.', chinese: '疏散', example: 'Evacuate the city.' },
  { id: 'u4-10', unit: 'Unit 4', english: 'helicopter', phonetic: '/ˈhelɪkɒptə(r)/', partOfSpeech: 'n.', chinese: '直升机', example: 'Fly a helicopter.' },
  { id: 'u4-11', unit: 'Unit 4', english: 'death', phonetic: '/deθ/', partOfSpeech: 'n.', chinese: '死亡', example: 'Cause death.' },
  { id: 'u4-12', unit: 'Unit 4', english: 'affect', phonetic: '/əˈfekt/', partOfSpeech: 'vt.', chinese: '影响', example: 'Affect the outcome.' },
  { id: 'u4-13', unit: 'Unit 4', english: 'shelter', phonetic: '/ˈʃeltə(r)/', partOfSpeech: 'n.', chinese: '避难所', example: 'Find shelter.' },
  { id: 'u4-14', unit: 'Unit 4', english: 'crack', phonetic: '/kræk/', partOfSpeech: 'n. & vi.', chinese: '裂纹；破裂', example: 'A crack in the wall.' },
  { id: 'u4-15', unit: 'Unit 4', english: 'ruin', phonetic: '/ruːɪn/', partOfSpeech: 'n. & vt.', chinese: '废墟', example: 'In ruins.' },
  { id: 'u4-16', unit: 'Unit 4', english: 'percent', phonetic: '/pəˈsent/', partOfSpeech: 'n.', chinese: '百分之...', example: 'Ten percent.' },
  { id: 'u4-17', unit: 'Unit 4', english: 'brick', phonetic: '/brɪk/', partOfSpeech: 'n.', chinese: '砖', example: 'Red brick.' },
  { id: 'u4-18', unit: 'Unit 4', english: 'metal', phonetic: '/ˈmetl/', partOfSpeech: 'n.', chinese: '金属', example: 'Made of metal.' },
  { id: 'u4-19', unit: 'Unit 4', english: 'shock', phonetic: '/ʃɒk/', partOfSpeech: 'n.', chinese: '震惊', example: 'In shock.' },
  { id: 'u4-20', unit: 'Unit 4', english: 'electricity', phonetic: '/ɪˌlekˈtrɪsəti/', partOfSpeech: 'n.', chinese: '电', example: 'Cut off electricity.' },
  { id: 'u4-21', unit: 'Unit 4', english: 'trap', phonetic: '/træp/', partOfSpeech: 'vt.', chinese: '困住', example: 'Trapped in a hole.' },
  { id: 'u4-22', unit: 'Unit 4', english: 'bury', phonetic: '/ˈberi/', partOfSpeech: 'vt.', chinese: '埋葬', example: 'Bury the treasure.' },
  { id: 'u4-23', unit: 'Unit 4', english: 'breathe', phonetic: '/briːð/', partOfSpeech: 'vi. & vt.', chinese: '呼吸', example: 'Breathe deeply.' },
  { id: 'u4-24', unit: 'Unit 4', english: 'revive', phonetic: '/rɪˈvaɪv/', partOfSpeech: 'vi. & vt.', chinese: '复苏', example: 'Revive the patient.' },
  { id: 'u4-25', unit: 'Unit 4', english: 'effort', phonetic: '/ˈefət/', partOfSpeech: 'n.', chinese: '努力', example: 'Make an effort.' },
  { id: 'u4-26', unit: 'Unit 4', english: 'wisdom', phonetic: '/ˈwɪzdəm/', partOfSpeech: 'n.', chinese: '智慧', example: 'Words of wisdom.' },
  { id: 'u4-27', unit: 'Unit 4', english: 'suffer', phonetic: '/ˈsʌfə(r)/', partOfSpeech: 'vi. & vt.', chinese: '遭受', example: 'Suffer from pain.' },
  { id: 'u4-28', unit: 'Unit 4', english: 'volcano', phonetic: '/vɒlˈkeɪnəʊ/', partOfSpeech: 'n.', chinese: '火山', example: 'Active volcano.' },
  { id: 'u4-29', unit: 'Unit 4', english: 'erupt', phonetic: '/ɪˈrʌpt/', partOfSpeech: 'vi.', chinese: '爆发', example: 'The volcano erupted.' },
  { id: 'u4-30', unit: 'Unit 4', english: 'supply', phonetic: '/səˈplaɪ/', partOfSpeech: 'n. & vt.', chinese: '供应', example: 'Food supply.' },
  { id: 'u4-31', unit: 'Unit 4', english: 'typhoon', phonetic: '/taɪˈfuːn/', partOfSpeech: 'n.', chinese: '台风', example: 'Typhoon warning.' },
  { id: 'u4-32', unit: 'Unit 4', english: 'hurricane', phonetic: '/ˈhʌrɪkən/', partOfSpeech: 'n.', chinese: '飓风', example: 'Hurricane season.' },
  { id: 'u4-33', unit: 'Unit 4', english: 'survive', phonetic: '/səˈvaɪv/', partOfSpeech: 'vi. & vt.', chinese: '幸存', example: 'Survive the crash.' },
  { id: 'u4-34', unit: 'Unit 4', english: 'power', phonetic: '/ˈpaʊə(r)/', partOfSpeech: 'n.', chinese: '电力；力量', example: 'Power cut.' },
  { id: 'u4-35', unit: 'Unit 4', english: 'emergency', phonetic: '/iˈmɜːdʒənsi/', partOfSpeech: 'n.', chinese: '紧急情况', example: 'In an emergency.' },
  { id: 'u4-36', unit: 'Unit 4', english: 'aid', phonetic: '/eɪd/', partOfSpeech: 'n. & vt.', chinese: '援助', example: 'First aid.' },
  { id: 'u4-37', unit: 'Unit 4', english: 'kit', phonetic: '/kɪt/', partOfSpeech: 'n.', chinese: '成套工具', example: 'First aid kit.' },
  { id: 'u4-38', unit: 'Unit 4', english: 'crash', phonetic: '/kræʃ/', partOfSpeech: 'vi. & vt.', chinese: '碰撞；坠毁', example: 'Car crash.' },
  { id: 'u4-39', unit: 'Unit 4', english: 'sweep', phonetic: '/swiːp/', partOfSpeech: 'vi. & vt.', chinese: '扫；席卷', example: 'Sweep the floor.' },
  { id: 'u4-40', unit: 'Unit 4', english: 'wave', phonetic: '/weɪv/', partOfSpeech: 'n. & vi.', chinese: '海浪；挥手', example: 'Huge wave.' },
  { id: 'u4-41', unit: 'Unit 4', english: 'strike', phonetic: '/straɪk/', partOfSpeech: 'vi. & vt.', chinese: '侵袭；打击', example: 'Disaster struck.' },
  { id: 'u4-42', unit: 'Unit 4', english: 'deliver', phonetic: '/dɪˈlɪvə(r)/', partOfSpeech: 'vt.', chinese: '递送', example: 'Deliver a letter.' },
  { id: 'u4-43', unit: 'Unit 4', english: 'summary', phonetic: '/ˈsʌməri/', partOfSpeech: 'n.', chinese: '总结', example: 'A brief summary.' },
  { id: 'u4-44', unit: 'Unit 4', english: 'effect', phonetic: '/ɪˈfekt/', partOfSpeech: 'n.', chinese: '影响；结果', example: 'Cause and effect.' },
  { id: 'u4-45', unit: 'Unit 4', english: 'length', phonetic: '/leŋθ/', partOfSpeech: 'n.', chinese: '长度', example: 'Length of time.' },

  // --- Unit 5: Languages Around the World ---
  { id: 'u5-1', unit: 'Unit 5', english: 'billion', phonetic: '/ˈbɪljən/', partOfSpeech: 'n.', chinese: '十亿', example: 'Two billion people.' },
  { id: 'u5-2', unit: 'Unit 5', english: 'native', phonetic: '/ˈneɪtɪv/', partOfSpeech: 'adj.', chinese: '本国的', example: 'Native speaker.' },
  { id: 'u5-3', unit: 'Unit 5', english: 'attitude', phonetic: '/ˈætɪtjuːd/', partOfSpeech: 'n.', chinese: '态度', example: 'Positive attitude.' },
  { id: 'u5-4', unit: 'Unit 5', english: 'reference', phonetic: '/ˈrefrəns/', partOfSpeech: 'n.', chinese: '参考', example: 'For reference only.' },
  { id: 'u5-5', unit: 'Unit 5', english: 'refer', phonetic: '/rɪˈfɜː(r)/', partOfSpeech: 'vi.', chinese: '提到；参考', example: 'Refer to the map.' },
  { id: 'u5-6', unit: 'Unit 5', english: 'system', phonetic: '/ˈsɪstəm/', partOfSpeech: 'n.', chinese: '系统', example: 'Computer system.' },
  { id: 'u5-7', unit: 'Unit 5', english: 'despite', phonetic: '/dɪˈspaɪt/', partOfSpeech: 'prep.', chinese: '尽管', example: 'Despite the rain.' },
  { id: 'u5-8', unit: 'Unit 5', english: 'factor', phonetic: '/ˈfæktə(r)/', partOfSpeech: 'n.', chinese: '因素', example: 'Key factor.' },
  { id: 'u5-9', unit: 'Unit 5', english: 'based', phonetic: '/beɪst/', partOfSpeech: 'adj.', chinese: '以...为基础的', example: 'Based on facts.' },
  { id: 'u5-10', unit: 'Unit 5', english: 'base', phonetic: '/beɪs/', partOfSpeech: 'vt. & n.', chinese: '基地；基础', example: 'Military base.' },
  { id: 'u5-11', unit: 'Unit 5', english: 'bone', phonetic: '/bəʊn/', partOfSpeech: 'n.', chinese: '骨头', example: 'Broken bone.' },
  { id: 'u5-12', unit: 'Unit 5', english: 'shell', phonetic: '/ʃel/', partOfSpeech: 'n.', chinese: '壳', example: 'Sea shell.' },
  { id: 'u5-13', unit: 'Unit 5', english: 'symbol', phonetic: '/ˈsɪmbl/', partOfSpeech: 'n.', chinese: '符号', example: 'Symbol of love.' },
  { id: 'u5-14', unit: 'Unit 5', english: 'carve', phonetic: '/kɑːv/', partOfSpeech: 'vt.', chinese: '雕刻', example: 'Carve wood.' },
  { id: 'u5-15', unit: 'Unit 5', english: 'dynasty', phonetic: '/ˈdɪnəsti/', partOfSpeech: 'n.', chinese: '朝代', example: 'Ming Dynasty.' },
  { id: 'u5-16', unit: 'Unit 5', english: 'variety', phonetic: '/vəˈraɪəti/', partOfSpeech: 'n.', chinese: '多样性；种类', example: 'A variety of food.' },
  { id: 'u5-17', unit: 'Unit 5', english: 'major', phonetic: '/ˈmeɪdʒə(r)/', partOfSpeech: 'adj.', chinese: '主要的', example: 'Major city.' },
  { id: 'u5-18', unit: 'Unit 5', english: 'dialect', phonetic: '/ˈdaɪəlekt/', partOfSpeech: 'n.', chinese: '方言', example: 'Local dialect.' },
  { id: 'u5-19', unit: 'Unit 5', english: 'means', phonetic: '/miːnz/', partOfSpeech: 'n.', chinese: '方式', example: 'Means of transport.' },
  { id: 'u5-20', unit: 'Unit 5', english: 'classic', phonetic: '/ˈklæsɪk/', partOfSpeech: 'adj.', chinese: '经典的', example: 'Classic movie.' },
  { id: 'u5-21', unit: 'Unit 5', english: 'regard', phonetic: '/rɪˈɡɑːd/', partOfSpeech: 'vt.', chinese: '看待', example: 'Regard as a friend.' },
  { id: 'u5-22', unit: 'Unit 5', english: 'character', phonetic: '/ˈkærəktə(r)/', partOfSpeech: 'n.', chinese: '汉字；性格', example: 'Chinese character.' },
  { id: 'u5-23', unit: 'Unit 5', english: 'calligraphy', phonetic: '/kəˈlɪɡrəfi/', partOfSpeech: 'n.', chinese: '书法', example: 'Chinese calligraphy.' },
  { id: 'u5-24', unit: 'Unit 5', english: 'global', phonetic: '/ˈɡləʊbl/', partOfSpeech: 'adj.', chinese: '全球的', example: 'Global warming.' },
  { id: 'u5-25', unit: 'Unit 5', english: 'affair', phonetic: '/əˈfeə(r)/', partOfSpeech: 'n.', chinese: '事务', example: 'Foreign affairs.' },
  { id: 'u5-26', unit: 'Unit 5', english: 'appreciate', phonetic: '/əˈpriːʃieɪt/', partOfSpeech: 'vt.', chinese: '欣赏；感激', example: 'Appreciate art.' },
  { id: 'u5-27', unit: 'Unit 5', english: 'specific', phonetic: '/spəˈsɪfɪk/', partOfSpeech: 'adj.', chinese: '具体的', example: 'Be specific.' },
  { id: 'u5-28', unit: 'Unit 5', english: 'struggle', phonetic: '/ˈstrʌɡl/', partOfSpeech: 'n. & vi.', chinese: '斗争；挣扎', example: 'Struggle to survive.' },
  { id: 'u5-29', unit: 'Unit 5', english: 'tongue', phonetic: '/tʌŋ/', partOfSpeech: 'n.', chinese: '舌头；语言', example: 'Mother tongue.' },
  { id: 'u5-30', unit: 'Unit 5', english: 'semester', phonetic: '/sɪˈmestə(r)/', partOfSpeech: 'n.', chinese: '学期', example: 'Spring semester.' },
  { id: 'u5-31', unit: 'Unit 5', english: 'gas', phonetic: '/ɡæs/', partOfSpeech: 'n.', chinese: '汽油；气体', example: 'Run out of gas.' },
  { id: 'u5-32', unit: 'Unit 5', english: 'petrol', phonetic: '/ˈpetrəl/', partOfSpeech: 'n.', chinese: '汽油', example: 'Petrol station.' },
  { id: 'u5-33', unit: 'Unit 5', english: 'subway', phonetic: '/ˈsʌbweɪ/', partOfSpeech: 'n.', chinese: '地铁', example: 'Take the subway.' },
  { id: 'u5-34', unit: 'Unit 5', english: 'apartment', phonetic: '/əˈpɑːtmənt/', partOfSpeech: 'n.', chinese: '公寓', example: 'Rent an apartment.' },
  { id: 'u5-35', unit: 'Unit 5', english: 'pants', phonetic: '/pænts/', partOfSpeech: 'n.', chinese: '裤子', example: 'A pair of pants.' },
  { id: 'u5-36', unit: 'Unit 5', english: 'beg', phonetic: '/beɡ/', partOfSpeech: 'vt.', chinese: '恳求', example: 'Beg for help.' },
  { id: 'u5-37', unit: 'Unit 5', english: 'equal', phonetic: '/ˈiːkwəl/', partOfSpeech: 'adj.', chinese: '平等的', example: 'Equal rights.' },
  { id: 'u5-38', unit: 'Unit 5', english: 'gap', phonetic: '/ɡæp/', partOfSpeech: 'n.', chinese: '差距；缺口', example: 'Generation gap.' },
  { id: 'u5-39', unit: 'Unit 5', english: 'demand', phonetic: '/dɪˈmɑːnd/', partOfSpeech: 'n. & vt.', chinese: '要求', example: 'Demand an answer.' },
  { id: 'u5-40', unit: 'Unit 5', english: 'vocabulary', phonetic: '/vəˈkæbjələri/', partOfSpeech: 'n.', chinese: '词汇', example: 'Large vocabulary.' },
  { id: 'u5-41', unit: 'Unit 5', english: 'description', phonetic: '/dɪˈskrɪpʃn/', partOfSpeech: 'n.', chinese: '描述', example: 'Detailed description.' },
  { id: 'u5-42', unit: 'Unit 5', english: 'relate', phonetic: '/rɪˈleɪt/', partOfSpeech: 'vi. & vt.', chinese: '联系', example: 'Relate to the topic.' }
];

// --- Comprehensive Exam Questions (Grammar / Structure) ---
export const EXAM_DATA: ExamQuestion[] = [
    // --- Welcome Unit ---
    {
        id: 'eq-wu-1',
        unit: 'Welcome Unit',
        type: 'GRAMMAR',
        question: 'He has an ______ personality and makes friends easily.',
        options: ['anxious', 'outgoing', 'awkward', 'annoyed'],
        correctAnswer: 1,
        explanation: "'outgoing' 意为“外向的”，符合语境“容易交朋友”。",
        hint: "这个人容易交朋友，说明性格开朗。"
    },
    {
        id: 'eq-wu-2',
        unit: 'Welcome Unit',
        type: 'GRAMMAR',
        question: 'I ______ meeting you in Beijing next month.',
        options: ['look forward to', 'look up to', 'look out for', 'look down on'],
        correctAnswer: 0,
        explanation: "'look forward to doing sth' 是固定搭配，意为“期待做某事”。",
        hint: "表示‘盼望’、‘期待’的短语。"
    },
    {
        id: 'eq-wu-3',
        unit: 'Welcome Unit',
        type: 'GRAMMAR',
        question: 'It is important to ______ on your studies in high school.',
        options: ['impress', 'design', 'concentrate', 'explore'],
        correctAnswer: 2,
        explanation: "'concentrate on' 意为“全神贯注于”。",
        hint: "把注意力集中在某事上。"
    },
    {
        id: 'eq-wu-4',
        unit: 'Welcome Unit',
        type: 'GRAMMAR',
        question: 'The ______ high school student is preparing for the exam.',
        options: ['senior', 'junior', 'fresh', 'young'],
        correctAnswer: 0,
        explanation: "'senior high school' 是高中。",
        hint: "对应 'Junior High' 的高级阶段。"
    },
    {
        id: 'eq-wu-5',
        unit: 'Welcome Unit',
        type: 'GRAMMAR',
        question: 'He wanted to ______ his teacher with his hard work.',
        options: ['impress', 'express', 'press', 'depress'],
        correctAnswer: 0,
        explanation: "'impress' 给...留下印象。",
        hint: "想让老师对自己印象深刻。"
    },

    // --- Unit 1: Teenage Life ---
    {
        id: 'eq-u1-1',
        unit: 'Unit 1',
        type: 'GRAMMAR',
        question: 'As a teenager, you should learn to be ______ for your own behavior.',
        options: ['responsible', 'confused', 'fluent', 'advanced'],
        correctAnswer: 0,
        explanation: "'be responsible for' 是固定短语，意为“对...负责”。",
        hint: "你需要为自己的行为‘买单’。"
    },
    {
        id: 'eq-u1-2',
        unit: 'Unit 1',
        type: 'GRAMMAR',
        question: 'The teacher recommends ______ English novels to improve vocabulary.',
        options: ['to read', 'reading', 'read', 'reads'],
        correctAnswer: 1,
        explanation: "'recommend doing sth' 意为“推荐做某事”。",
        hint: "Recommend 后接动名词。"
    },
    {
        id: 'eq-u1-3',
        unit: 'Unit 1',
        type: 'GRAMMAR',
        question: 'He felt ______ about the complex math problem.',
        options: ['confusing', 'confused', 'confuse', 'confuses'],
        correctAnswer: 1,
        explanation: "修饰人通常用 -ed 结尾的形容词。",
        hint: "描述人的感受用 -ed。"
    },
    {
        id: 'eq-u1-4',
        unit: 'Unit 1',
        type: 'GRAMMAR',
        question: '______ cleaning the classroom, he went home.',
        options: ['After finish', 'After finishing', 'To finish', 'Finished'],
        correctAnswer: 1,
        explanation: "After 是介词，后面跟动名词 finishing。",
        hint: "介词后跟动名词。"
    },
    {
        id: 'eq-u1-5',
        unit: 'Unit 1',
        type: 'GRAMMAR',
        question: 'I prefer tea ______ coffee.',
        options: ['to', 'than', 'for', 'with'],
        correctAnswer: 0,
        explanation: "'prefer A to B' 喜欢A多于B。",
        hint: "Prefer ... ___ ..."
    },

    // --- Unit 2: Travelling Around ---
    {
        id: 'eq-u2-1',
        unit: 'Unit 2',
        type: 'GRAMMAR',
        question: 'We need to make ______ for the school trip in advance.',
        options: ['arrangements', 'flights', 'destinations', 'civilisations'],
        correctAnswer: 0,
        explanation: "'make arrangements for' 意为“为...做安排”。",
        hint: "旅行前需要做的‘准备工作’。"
    },
    {
        id: 'eq-u2-2',
        unit: 'Unit 2',
        type: 'GRAMMAR',
        question: 'The castle ______ in the 16th century is still well-preserved.',
        options: ['building', 'built', 'build', 'to build'],
        correctAnswer: 1,
        explanation: "过去分词做后置定语，表被动。",
        hint: "城堡是‘被’建造的。"
    },
    {
        id: 'eq-u2-3',
        unit: 'Unit 2',
        type: 'GRAMMAR',
        question: 'This is the hotel ______ we stayed last year.',
        options: ['which', 'that', 'where', 'when'],
        correctAnswer: 2,
        explanation: "定语从句中，先行词 hotel 表地点且从句完整。",
        hint: "先行词是地点，从句不缺主宾。"
    },
    {
        id: 'eq-u2-4',
        unit: 'Unit 2',
        type: 'GRAMMAR',
        question: 'I\'ll ______ for a visa next week.',
        options: ['apply', 'reply', 'supply', 'imply'],
        correctAnswer: 0,
        explanation: "'apply for a visa' 申请签证。",
        hint: "出国前需要办理的文件。"
    },
    {
        id: 'eq-u2-5',
        unit: 'Unit 2',
        type: 'GRAMMAR',
        question: 'Can you ______ me in this old photo?',
        options: ['realise', 'recognise', 'know', 'watch'],
        correctAnswer: 1,
        explanation: "'recognise' 认出。",
        hint: "辨认出某人。"
    },

    // --- Unit 3: Sports and Fitness ---
    {
        id: 'eq-u3-1',
        unit: 'Unit 3',
        type: 'GRAMMAR',
        question: '______ hard, he won the first prize.',
        options: ['Work', 'Working', 'Worked', 'To work'],
        correctAnswer: 1,
        explanation: "现在分词做状语，表主动。",
        hint: "主动努力训练。"
    },
    {
        id: 'eq-u3-2',
        unit: 'Unit 3',
        type: 'GRAMMAR',
        question: 'The athlete didn\'t give up ______ he failed many times.',
        options: ['even if', 'as if', 'so that', 'in case'],
        correctAnswer: 0,
        explanation: "'even if' 即使。",
        hint: "引导让步状语从句。"
    },
    {
        id: 'eq-u3-3',
        unit: 'Unit 3',
        type: 'GRAMMAR',
        question: 'She pretends ______ the answer.',
        options: ['knowing', 'to know', 'know', 'knew'],
        correctAnswer: 1,
        explanation: "'pretend to do sth' 假装做某事。",
        hint: "Pretend 后接不定式。"
    },
    {
        id: 'eq-u3-4',
        unit: 'Unit 3',
        type: 'GRAMMAR',
        question: 'He decided to quit ______ junk food.',
        options: ['eat', 'to eat', 'eating', 'ate'],
        correctAnswer: 2,
        explanation: "'quit doing' 停止做某事。",
        hint: "Quit 后接动名词。"
    },
    {
        id: 'eq-u3-5',
        unit: 'Unit 3',
        type: 'GRAMMAR',
        question: 'I play sports to lose weight rather ______ for fun.',
        options: ['than', 'then', 'that', 'this'],
        correctAnswer: 0,
        explanation: "'rather than' 而不是。",
        hint: "表示‘而不是’。"
    },
    
    // --- Unit 4: Natural Disasters ---
    {
        id: 'eq-u4-1',
        unit: 'Unit 4',
        type: 'GRAMMAR',
        question: 'The house ______ by the flood needs repair.',
        options: ['damaging', 'damaged', 'damage', 'to damage'],
        correctAnswer: 1,
        explanation: "过去分词做后置定语，表被动。",
        hint: "房子是‘被’破坏的。"
    },
    {
        id: 'eq-u4-2',
        unit: 'Unit 4',
        type: 'GRAMMAR',
        question: '______ from the hill, the city looks beautiful.',
        options: ['Seeing', 'Seen', 'See', 'To see'],
        correctAnswer: 1,
        explanation: "过去分词做状语，主语是 city，表被动。",
        hint: "城市是被看见的。"
    },
    {
        id: 'eq-u4-3',
        unit: 'Unit 4',
        type: 'GRAMMAR',
        question: 'Supplies ______ to the area yesterday.',
        options: ['sent', 'were sent', 'are sent', 'send'],
        correctAnswer: 1,
        explanation: "一般过去时的被动语态。",
        hint: "发生在过去且是被动。"
    },
    {
        id: 'eq-u4-4',
        unit: 'Unit 4',
        type: 'GRAMMAR',
        question: 'Many people ______ from the earthquake.',
        options: ['suffered', 'offered', 'destroyed', 'ruined'],
        correctAnswer: 0,
        explanation: "'suffer from' 遭受。",
        hint: "遭受灾难。"
    },
    {
        id: 'eq-u4-5',
        unit: 'Unit 4',
        type: 'GRAMMAR',
        question: 'They were ______ in the ruins for hours.',
        options: ['trapped', 'trap', 'trapping', 'to trap'],
        correctAnswer: 0,
        explanation: "'be trapped' 被困住。",
        hint: "被动语态。"
    },

    // --- Unit 5: Languages Around the World ---
    {
        id: 'eq-u5-1',
        unit: 'Unit 5',
        type: 'GRAMMAR',
        question: 'Factors ______ to the development of language.',
        options: ['related', 'relating', 'relate', 'to relate'],
        correctAnswer: 1,
        explanation: "'relating to' 与...相关 (主动)。",
        hint: "现在分词做定语。"
    },
    {
        id: 'eq-u5-2',
        unit: 'Unit 5',
        type: 'GRAMMAR',
        question: 'No matter ______ difficult it is, don\'t give up.',
        options: ['what', 'how', 'when', 'where'],
        correctAnswer: 1,
        explanation: "'No matter how' + adj.",
        hint: "修饰形容词 difficult。"
    },
    {
        id: 'eq-u5-3',
        unit: 'Unit 5',
        type: 'GRAMMAR',
        question: 'Symbols ______ date back thousands of years.',
        options: ['who', 'which', 'where', 'whose'],
        correctAnswer: 1,
        explanation: "定语从句修饰物 symbols。",
        hint: "先行词是物。"
    },
    {
        id: 'eq-u5-4',
        unit: 'Unit 5',
        type: 'GRAMMAR',
        question: 'Please ______ to the map on page 10.',
        options: ['refer', 'prefer', 'infer', 'offer'],
        correctAnswer: 0,
        explanation: "'refer to' 参考；查阅。",
        hint: "查看地图。"
    },
    {
        id: 'eq-u5-5',
        unit: 'Unit 5',
        type: 'GRAMMAR',
        question: 'The carving dates ______ to the Han Dynasty.',
        options: ['back', 'up', 'down', 'away'],
        correctAnswer: 0,
        explanation: "'date back to' 追溯到。",
        hint: "追溯到某个时间点。"
    },
];

export const LIBRARY_STRUCTURE: LibraryCategory[] = [
  {
    id: 'compulsory_1',
    name: '必修第一册',
    description: 'Textbook 1',
    units: ['Welcome Unit', 'Unit 1', 'Unit 2', 'Unit 3', 'Unit 4', 'Unit 5', '全册综合测试']
  },
  {
    id: 'compulsory_2',
    name: '必修第二册',
    description: 'Coming Soon',
    units: [] 
  },
  {
    id: 'writing_skills',
    name: '写作积累',
    description: 'Essay Skills',
    units: [] 
  },
  {
    id: 'exam_prep',
    name: '高考备考',
    description: 'Exam Prep',
    units: [] 
  }
];

export const UNITS = Array.from(new Set(VOCABULARY_DATA.map(w => w.unit)));

export const getWordsByUnit = (unit: string) => VOCABULARY_DATA.filter(w => w.unit === unit);
export const getExamQuestionsByUnit = (unit: string) => EXAM_DATA.filter(q => q.unit === unit);